not1 = int (input("entrez not1 :"))
not2 = int (input("entrez not2 :"))
coef1 = int(input("entrez coef1 :"))
coef2 = int(input("enrtrez coef2 : "))
moyenne =(not1*coef1 + not2*coef2)/(coef1+coef2)
print(f"moyenne : {moyenne:.2f}")